# spring configuration
spring:
   application:
      name: mysite06
   
   # devtool
   devtools:
      restart: 
         enabled: true
      livereload:
         enabled: true
 
   main:
      allow-bean-definition-overriding: true
   
# server configuration
server:
   port: 8080
   servlet: 
      context-path: /mysite06